build:
  - echo "deb http://www.rabbitmq.com/debian/ testing main" >> /etc/apt/sources.list
  - curl http://www.rabbitmq.com/rabbitmq-signing-key-public.asc | apt-key add -
  - echo "deb http://dl.hhvm.com/ubuntu saucy main" >> /etc/apt/sources.list
  - apt-get update -y
  - apt-get install -y --force-yes rabbitmq-server hhvm php-apc
  - composer install --no-dev --ansi --prefer-source --no-progress --no-interaction
  - app/console assetic:dump

run:
  - /etc/init.d/rabbitmq-server start
  - while true; do /var/www/app/console sonata:notification:start; sleep 5; done;
