language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

env:
    # repository pborreli/composer-service
    # PUSHER_APP_ID= PUSHER_KEY= PUSHER_SECRET=
    - secure: "LwnKMDhBUzxPhbDvBzpdHK6NjXPMlS4gR5ulHKLvcMGnYkpTdiLonOeaC3iNvk3GoFmPjscFrl5YWfy/jh5vg5tUHy8FB3oue3j0GgjiVXRWZa/ccJLjySNfLNTVfmzSNkOxEDRLC3CYIIUK/FPumPBF4g72xLfRT3Zux9PAszw="

services: rabbitmq

before_script:
    - sudo apt-get update
    - sudo apt-get install -y --force-yes apache2 libapache2-mod-php5 php5-mysql php5-curl php5-intl
    - sudo sed -i -e "s,/var/www,$(pwd)/web,g" /etc/apache2/sites-available/default
    - export MINK_EXTENSION_PARAMS='base_url=http://localhost/app_test.php'
    - sudo /etc/init.d/apache2 restart
    - composer self-update
    - composer install -n --dev --prefer-dist
    - chmod -R 777 app/cache app/logs
    - app/console --env=test cache:warmup
    - chmod -R 777 app/cache app/logs
    - php app/console --env=test sonata:notification:start > /dev/null &
    - export DISPLAY=:99
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.39.0.jar
    - java -jar selenium-server-standalone-2.39.0.jar > /dev/null &
    - sh -e /etc/init.d/xvfb start
    - sleep 5

script:
    - bin/behat --format=pretty --verbose --stop-on-failure
    - phpunit -c app
